# Pandas

In [3]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
grades = {"Furkan":50,"James":60,"Lars":30}

In [5]:
pd.Series(grades)

Furkan    50
James     60
Lars      30
dtype: int64

In [8]:
names = ["Furkan","james","Lars"]
grades = [50,60,30]

In [9]:
pd.Series(names)

0    Furkan
1     james
2      Lars
dtype: object

In [9]:
pd.Series(grades)

0    50
1    60
2    30
dtype: int64

In [10]:
pd.Series(grades,names)

Furkan    50
james     60
Lars      30
dtype: int64

In [11]:
pd.Series(data=grades,index=names)

Furkan    50
james     60
Lars      30
dtype: int64

# with numpy

In [12]:
numpy_array = np.array([50,40,30,20])

In [13]:
pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int64

In [14]:
#arithmetic
contest_result1= pd.Series([10,5,100],["Furkan","James","Lars"])

In [15]:
#arithmetic
contest_result2= pd.Series([20,50,10],["Furkan","James","Lars"])

In [16]:
contest_result

Furkan     10
James       5
Lars      100
dtype: int64

In [17]:
contest_result["Furkan"]

np.int64(10)

In [18]:
contest_result2["James"]

np.int64(50)

In [19]:
final_result = contest_result + contest_result2

In [20]:
final_result

Furkan     30
James      55
Lars      110
dtype: int64

In [21]:
contest_result * contest_result2

Furkan     200
James      250
Lars      1000
dtype: int64

In [22]:
contest_result / contest_result2

Furkan     0.5
James      0.1
Lars      10.0
dtype: float64

In [23]:
different_series = pd.Series([20,30,40,50],["a","b","c","d"])

In [24]:
different_series

a    20
b    30
c    40
d    50
dtype: int64

In [25]:
different_series2 = pd.Series([10,5,3,1],["a","c","f","g"])

In [26]:
different_series2

a    10
c     5
f     3
g     1
dtype: int64

In [27]:
different_series + different_series2

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64

In [16]:
import pandas as pd

In [17]:
ages = pd.Series([22, 25, 31, 28, 35])

In [20]:
print(ages)

0    22
1    25
2    31
3    28
4    35
dtype: int64

In [22]:
type(ages)

pandas.core.series.Series

In [23]:
ages = pd.Series([22, 25, 31, 28, 35])

In [24]:
ages[0]

np.int64(22)

In [25]:
data = { "Name": ["Ali","Ahmet","Mehmet"], 
         "Age": [25, 29, 31], 
         "City": ["İstanbul", "Ankara", "İzmir"] }

In [26]:
df = pd.DataFrame(data)

In [27]:
df

     Name  Age      City
0     Ali   25  İstanbul
1   Ahmet   29    Ankara
2  Mehmet   31     İzmir

In [31]:
df[["Name","Age"]]

     Name  Age
0     Ali   25
1   Ahmet   29
2  Mehmet   31

In [33]:
df.iloc[0]

Name         Ali
Age           25
City    İstanbul
Name: 0, dtype: object

In [34]:
df.iloc[0:3]

     Name  Age      City
0     Ali   25  İstanbul
1   Ahmet   29    Ankara
2  Mehmet   31     İzmir

In [37]:
df.loc[:,["Name","Age"]]

     Name  Age
0     Ali   25
1   Ahmet   29
2  Mehmet   31

In [39]:
df.index = ["a", "b", "c"]

In [40]:
df

     Name  Age      City
a     Ali   25  İstanbul
b   Ahmet   29    Ankara
c  Mehmet   31     İzmir

In [28]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [41]:
df.loc["b"]

Name     Ahmet
Age         29
City    Ankara
Name: b, dtype: object

In [42]:
df["Passed"] = True

In [43]:
df

     Name  Age      City  Passed
a     Ali   25  İstanbul    True
b   Ahmet   29    Ankara    True
c  Mehmet   31     İzmir    True

In [44]:
df["Age_2"] = df["Age"] *2

In [45]:
df

     Name  Age      City  Passed  Age_2
a     Ali   25  İstanbul    True     50
b   Ahmet   29    Ankara    True     58
c  Mehmet   31     İzmir    True     62

In [47]:
df["Score"] =[30,40,50]

In [48]:
df

     Name  Age      City  Passed  Age_2  Score
a     Ali   25  İstanbul    True     50     30
b   Ahmet   29    Ankara    True     58     40
c  Mehmet   31     İzmir    True     62     50

In [49]:
df["Age_Score"] = df["Age"] + df["Score"]

In [50]:
df

     Name  Age      City  Passed  Age_2  Score  Age_Score
a     Ali   25  İstanbul    True     50     30         55
b   Ahmet   29    Ankara    True     58     40         69
c  Mehmet   31     İzmir    True     62     50         81

In [55]:
df.loc["a","Age"] = 60

In [56]:
df

     Name   Age      City Passed  Age_2  Score  Age_Score
a     Ali  60.0  İstanbul   True   50.0   30.0       55.0
b   Ahmet  29.0    Ankara   True   58.0   40.0       69.0
c  Mehmet  31.0     İzmir   True   62.0   50.0       81.0
0     NaN  60.0       NaN    NaN    NaN    NaN        NaN

In [29]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [57]:
df.rename(
    columns={"City":"Şehir"},
    inplace=True
)

In [58]:
df

     Name   Age     Şehir Passed  Age_2  Score  Age_Score
a     Ali  60.0  İstanbul   True   50.0   30.0       55.0
b   Ahmet  29.0    Ankara   True   58.0   40.0       69.0
c  Mehmet  31.0     İzmir   True   62.0   50.0       81.0
0     NaN  60.0       NaN    NaN    NaN    NaN        NaN