# 8-DataFramesApply

In [3]:
import pandas as pd

In [33]:
pd = pd.read_csv("8-apply_function_data.csv")

AttributeError: 'DataFrame' object has no attribute 'read_csv'

In [34]:
df

NameError: name 'df' is not defined

In [35]:
pd.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [36]:
pd.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [37]:
pd.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [38]:
pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [39]:
pd.isna()

    Employee_ID   Name  Department  Salary  Experience  Performance_Score
0         False  False       False   False       False              False
1         False  False       False   False       False              False
2         False  False       False   False       False              False
3         False  False       False   False       False              False
4         False  False       False   False       False              False
..          ...    ...         ...     ...         ...                ...
95        False  False       False   False       False              False
96        False  False       False   False       False              False
97        False  False       False   False       False              False
98        False  False       False   False       False              False
99        False  False       False   False       False              False

[100 rows x 6 columns]

In [40]:
pd.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [41]:
pd[1:20]

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5

In [43]:
 pd["Salary"].mean()

np.float64(77508.09)

In [44]:
def salary_category(salary):
    if salary < 50000:
        return "Low"
    elif 50000 <= salary < 80000:
        return "medium"
    else:
        return "High"

In [45]:
pd["Salary"].apply(salary_category)

0       High
1     medium
2        Low
3     medium
4       High
       ...
95      High
96      High
97      High
98       Low
99    medium
Name: Salary, Length: 100, dtype: object

In [47]:
pd["Salary_Category"] = pd["Salary"].apply(salary_category)

In [48]:
pd

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,High
1,2,Emp_2,Sales,52662,24,3,medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,High
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,medium

In [ ]:
# NewScore -> experince 10dan fazla ise performanca score +1

In [95]:
def new_Score(Experience):
    if Experience > 10:
       return  1
        
    else:
        return 0

In [96]:
pd["New Score"] = pd["Performance_Score"].apply(new_Score)

In [97]:
pd

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,YeniPuan,New Score
0,1,Emp_1,Marketing,82251,6,5,High,Experince not greater 10 years,0
1,2,Emp_2,Sales,52662,24,3,medium,1,0
2,3,Emp_3,Finance,38392,5,3,Low,Experince not greater 10 years,0
3,4,Emp_4,Sales,60535,20,3,medium,1,0
4,5,Emp_5,Sales,108603,2,2,High,Experince not greater 10 years,0
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,0
96,97,Emp_97,Sales,100467,22,2,High,1,0
97,98,Emp_98,IT,82662,23,3,High,1,0
98,99,Emp_99,IT,42688,22,1,Low,1,0
99,100,Emp_100,HR,55342,14,3,medium,1,0

In [98]:
pd

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,YeniPuan,New Score
0,1,Emp_1,Marketing,82251,6,5,High,Experince not greater 10 years,0
1,2,Emp_2,Sales,52662,24,3,medium,1,0
2,3,Emp_3,Finance,38392,5,3,Low,Experince not greater 10 years,0
3,4,Emp_4,Sales,60535,20,3,medium,1,0
4,5,Emp_5,Sales,108603,2,2,High,Experince not greater 10 years,0
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,0
96,97,Emp_97,Sales,100467,22,2,High,1,0
97,98,Emp_98,IT,82662,23,3,High,1,0
98,99,Emp_99,IT,42688,22,1,Low,1,0
99,100,Emp_100,HR,55342,14,3,medium,1,0

In [100]:
pd["New_Scoree"] = pd["Performance_Score"] + pd["New Score"]

In [101]:
pd

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,YeniPuan,New Score,New_Scoree
0,1,Emp_1,Marketing,82251,6,5,High,Experince not greater 10 years,0,5
1,2,Emp_2,Sales,52662,24,3,medium,1,0,3
2,3,Emp_3,Finance,38392,5,3,Low,Experince not greater 10 years,0,3
3,4,Emp_4,Sales,60535,20,3,medium,1,0,3
4,5,Emp_5,Sales,108603,2,2,High,Experince not greater 10 years,0,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,0,4
96,97,Emp_97,Sales,100467,22,2,High,1,0,2
97,98,Emp_98,IT,82662,23,3,High,1,0,3
98,99,Emp_99,IT,42688,22,1,Low,1,0,1
99,100,Emp_100,HR,55342,14,3,medium,1,0,3

In [105]:
def adjust_new(row):
    if row["Experience"] > 10:
        return row["Performance_Score"] +1
    else:
        return row["Performance_Score"]

In [106]:
pd["Adjust_Score"] = pd.apply(adjust_new,axis=1)

In [107]:
pd

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,YeniPuan,New Score,New_Scoree,Adjust_Score
0,1,Emp_1,Marketing,82251,6,5,High,Experince not greater 10 years,0,5,5
1,2,Emp_2,Sales,52662,24,3,medium,1,0,3,4
2,3,Emp_3,Finance,38392,5,3,Low,Experince not greater 10 years,0,3,3
3,4,Emp_4,Sales,60535,20,3,medium,1,0,3,4
4,5,Emp_5,Sales,108603,2,2,High,Experince not greater 10 years,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,0,4,5
96,97,Emp_97,Sales,100467,22,2,High,1,0,2,3
97,98,Emp_98,IT,82662,23,3,High,1,0,3,4
98,99,Emp_99,IT,42688,22,1,Low,1,0,1,2
99,100,Emp_100,HR,55342,14,3,medium,1,0,3,4

In [108]:
pd["Formatted_Name"] = pd["Name"].apply(lambda x: x.replace("_"," "))

In [109]:
pd

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,YeniPuan,New Score,New_Scoree,Adjust_Score,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,High,Experince not greater 10 years,0,5,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,medium,1,0,3,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,Experince not greater 10 years,0,3,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,medium,1,0,3,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,Experince not greater 10 years,0,2,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,0,4,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,1,0,2,3,Emp 97
97,98,Emp_98,IT,82662,23,3,High,1,0,3,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,1,0,1,2,Emp 99
99,100,Emp_100,HR,55342,14,3,medium,1,0,3,4,Emp 100